= 2. Method
The applied method for this thesis is design science research (DSR). We choose DSR because of its natural fit when creating an software artefact. DSR is described by vom Brocke et al @introduction-to-design-research as a paradigm which seeks to enhance knowledge through the creation of an innovative artefact. vom Brock et al @introduction-to-design-research explains further that the aim of DSR is to generate knowledge about how things can and should be constructed, this knowledge is referred to as design knowledge within the DSR paradigm.
== 2.1 Research project
The company Neurawave @neurawave presented the need for being able to collect health metrics that could be used for migraine prediction using machine learning. The requirements provided by Neurawave was that the data collection mechanism had to be integrated into their cross platform mobile application. We started by precisely defining the problem, and came to the conclusion that implementing design science would be the most suitable method to use when creating this software artefact. We have also decided to follow the design science reasearch methodology outlined by Peffers et al @design-science-research-methodology. The next step in our project will be to define the objectives of the solution, which needs to be closely tied as solutions to the specified problem that the design research is aimed at solving. During the definition of the objectives we will also conduct litterature research to gather knowledge about the current solutions and the state of the defined problem. The next step will be to to create the actual artefact, in our case it means designing and developing the actual data gathering solution. The development will be performed in an iterative manner and includes both the creation of the software and determening the desired functionality. When the artefact has been developed, we will demonstrate its ability to solve any part of the defined problem through experimentation or simulation. We will then evaluate the demonstrated abilitys capability of solving any part of the problem, probably through comparison of the artefacts functionality and the objectives defined as important for solving the problem. This design and implement, demonstrate and evaluate cycle will iteratively be performed  until desired state has been achieved.
== 2.2 Research methods
We plan to do initial open-ended interviews with the creators of the company to get the most information possible about the needs that might be unfulfilled with the current available solutions. As described by Hamza Alshenqeeti @interviewing-as-a-data-collection-method, the expected result from conducting interviewing as a qualitative research method is to "broaden the scope of understanding investigated phenomena". We decided to do the intitial information gathering as open-ended as possible in comparison to structured interviewing which takes a more quantitative form @interviewing-as-a-data-collection-method. Other methods such as questioniares was not seen as an alternative due to the quantitative nature of questionnaires @questionnaire-designing-for-a-survey, and since we wanted to gather the stakeholders thoughts and experiences, we decided that a more qualitative method would be more suitable.

After the initial open-ended interviews we decided to conduct literature research as a means of gaining more contextual information and expand our understanding in regards of the current state of the described problem area as described by Robinson et al, @literature-reviews-vs-systematic-reviews. Literature research is the act of searching for general information that might cover several aspects of a topic and is not as guided or strict as the systematic review. Systematic reviews in contrast is a directed review process of a precise research question with the purpose of generating evidence for a piece of research @literature-reviews-vs-systematic-reviews.

#bibliography("refs.yml")
