// Mocks generated by Mockito 5.4.6 from annotations
// in wearable_health/test/service/health_connect/hc_data_factory_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;
import 'package:wearable_health/service/converters/json/json_converter_interface.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDateTime_0 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [JsonConverter].
///
/// See the documentation for Mockito's code generation for more information.
class MockJsonConverter extends _i1.Mock implements _i2.JsonConverter {
  MockJsonConverter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<dynamic, dynamic> extractMap(dynamic value, String? errMsg) =>
      (super.noSuchMethod(
            Invocation.method(#extractMap, [value, errMsg]),
            returnValue: <dynamic, dynamic>{},
          )
          as Map<dynamic, dynamic>);

  @override
  Map<String, dynamic> extractJsonObject(
    Map<dynamic, dynamic>? data,
    String? errMsg,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#extractJsonObject, [data, errMsg]),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  Map<String, List<Map<String, dynamic>>>
  extractJsonObjectWithListOfJsonObjects(dynamic value, String? errMsg) =>
      (super.noSuchMethod(
            Invocation.method(#extractJsonObjectWithListOfJsonObjects, [
              value,
              errMsg,
            ]),
            returnValue: <String, List<Map<String, dynamic>>>{},
          )
          as Map<String, List<Map<String, dynamic>>>);

  @override
  List<dynamic> extractList(dynamic value, String? errMsg) =>
      (super.noSuchMethod(
            Invocation.method(#extractList, [value, errMsg]),
            returnValue: <dynamic>[],
          )
          as List<dynamic>);

  @override
  List<Map<String, dynamic>> extractListOfJsonObjects(
    dynamic value,
    String? errMsg,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#extractListOfJsonObjects, [value, errMsg]),
            returnValue: <Map<String, dynamic>>[],
          )
          as List<Map<String, dynamic>>);

  @override
  String extractStringValue(dynamic value, String? errMsg) =>
      (super.noSuchMethod(
            Invocation.method(#extractStringValue, [value, errMsg]),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.method(#extractStringValue, [value, errMsg]),
            ),
          )
          as String);

  @override
  int extractIntValue(dynamic value, String? errMsg) =>
      (super.noSuchMethod(
            Invocation.method(#extractIntValue, [value, errMsg]),
            returnValue: 0,
          )
          as int);

  @override
  double extractDoubleValue(dynamic value, String? errMsg) =>
      (super.noSuchMethod(
            Invocation.method(#extractDoubleValue, [value, errMsg]),
            returnValue: 0.0,
          )
          as double);

  @override
  DateTime extractDateTime(dynamic value, String? errMsg) =>
      (super.noSuchMethod(
            Invocation.method(#extractDateTime, [value, errMsg]),
            returnValue: _FakeDateTime_0(
              this,
              Invocation.method(#extractDateTime, [value, errMsg]),
            ),
          )
          as DateTime);

  @override
  DateTime extractDateTimeFromEpochMs(dynamic value, String? errMsg) =>
      (super.noSuchMethod(
            Invocation.method(#extractDateTimeFromEpochMs, [value, errMsg]),
            returnValue: _FakeDateTime_0(
              this,
              Invocation.method(#extractDateTimeFromEpochMs, [value, errMsg]),
            ),
          )
          as DateTime);
}
