// Mocks generated by Mockito 5.4.6 from annotations
// in wearable_health/test/service/health_kit/health_kit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:flutter/src/services/binary_messenger.dart' as _i3;
import 'package:flutter/src/services/message_codec.dart' as _i2;
import 'package:flutter/src/services/platform_channel.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:wearable_health/model/health_kit/hk_body_temperature.dart'
    as _i5;
import 'package:wearable_health/model/health_kit/hk_heart_rate.dart' as _i4;
import 'package:wearable_health/service/converters/json/json_converter_interface.dart'
    as _i10;
import 'package:wearable_health/service/health_kit/data_factory_interface.dart'
    as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMethodCodec_0 extends _i1.SmartFake implements _i2.MethodCodec {
  _FakeMethodCodec_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBinaryMessenger_1 extends _i1.SmartFake
    implements _i3.BinaryMessenger {
  _FakeBinaryMessenger_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHKHeartRate_2 extends _i1.SmartFake implements _i4.HKHeartRate {
  _FakeHKHeartRate_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHKBodyTemperature_3 extends _i1.SmartFake
    implements _i5.HKBodyTemperature {
  _FakeHKBodyTemperature_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDateTime_4 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MethodChannel].
///
/// See the documentation for Mockito's code generation for more information.
class MockMethodChannel extends _i1.Mock implements _i6.MethodChannel {
  MockMethodChannel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _i7.dummyValue<String>(this, Invocation.getter(#name)),
          )
          as String);

  @override
  _i2.MethodCodec get codec =>
      (super.noSuchMethod(
            Invocation.getter(#codec),
            returnValue: _FakeMethodCodec_0(this, Invocation.getter(#codec)),
          )
          as _i2.MethodCodec);

  @override
  _i3.BinaryMessenger get binaryMessenger =>
      (super.noSuchMethod(
            Invocation.getter(#binaryMessenger),
            returnValue: _FakeBinaryMessenger_1(
              this,
              Invocation.getter(#binaryMessenger),
            ),
          )
          as _i3.BinaryMessenger);

  @override
  _i8.Future<T?> invokeMethod<T>(String? method, [dynamic arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#invokeMethod, [method, arguments]),
            returnValue: _i8.Future<T?>.value(),
          )
          as _i8.Future<T?>);

  @override
  _i8.Future<List<T>?> invokeListMethod<T>(
    String? method, [
    dynamic arguments,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#invokeListMethod, [method, arguments]),
            returnValue: _i8.Future<List<T>?>.value(),
          )
          as _i8.Future<List<T>?>);

  @override
  _i8.Future<Map<K, V>?> invokeMapMethod<K, V>(
    String? method, [
    dynamic arguments,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#invokeMapMethod, [method, arguments]),
            returnValue: _i8.Future<Map<K, V>?>.value(),
          )
          as _i8.Future<Map<K, V>?>);

  @override
  void setMethodCallHandler(
    _i8.Future<dynamic> Function(_i2.MethodCall)? handler,
  ) => super.noSuchMethod(
    Invocation.method(#setMethodCallHandler, [handler]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [HKDataFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockHKDataFactory extends _i1.Mock implements _i9.HKDataFactory {
  MockHKDataFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.HKHeartRate createHeartRate(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#createHeartRate, [data]),
            returnValue: _FakeHKHeartRate_2(
              this,
              Invocation.method(#createHeartRate, [data]),
            ),
          )
          as _i4.HKHeartRate);

  @override
  _i5.HKBodyTemperature createBodyTemperature(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#createBodyTemperature, [data]),
            returnValue: _FakeHKBodyTemperature_3(
              this,
              Invocation.method(#createBodyTemperature, [data]),
            ),
          )
          as _i5.HKBodyTemperature);
}

/// A class which mocks [JsonConverter].
///
/// See the documentation for Mockito's code generation for more information.
class MockJsonConverter extends _i1.Mock implements _i10.JsonConverter {
  MockJsonConverter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<dynamic, dynamic> extractMap(dynamic value, String? errMsg) =>
      (super.noSuchMethod(
            Invocation.method(#extractMap, [value, errMsg]),
            returnValue: <dynamic, dynamic>{},
          )
          as Map<dynamic, dynamic>);

  @override
  Map<String, dynamic> extractJsonObject(
    Map<dynamic, dynamic>? data,
    String? errMsg,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#extractJsonObject, [data, errMsg]),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  Map<String, List<Map<String, dynamic>>>
  extractJsonObjectWithListOfJsonObjects(dynamic value, String? errMsg) =>
      (super.noSuchMethod(
            Invocation.method(#extractJsonObjectWithListOfJsonObjects, [
              value,
              errMsg,
            ]),
            returnValue: <String, List<Map<String, dynamic>>>{},
          )
          as Map<String, List<Map<String, dynamic>>>);

  @override
  List<dynamic> extractList(dynamic value, String? errMsg) =>
      (super.noSuchMethod(
            Invocation.method(#extractList, [value, errMsg]),
            returnValue: <dynamic>[],
          )
          as List<dynamic>);

  @override
  List<Map<String, dynamic>> extractListOfJsonObjects(
    dynamic value,
    String? errMsg,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#extractListOfJsonObjects, [value, errMsg]),
            returnValue: <Map<String, dynamic>>[],
          )
          as List<Map<String, dynamic>>);

  @override
  String extractStringValue(dynamic value, String? errMsg) =>
      (super.noSuchMethod(
            Invocation.method(#extractStringValue, [value, errMsg]),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#extractStringValue, [value, errMsg]),
            ),
          )
          as String);

  @override
  int extractIntValue(dynamic value, String? errMsg) =>
      (super.noSuchMethod(
            Invocation.method(#extractIntValue, [value, errMsg]),
            returnValue: 0,
          )
          as int);

  @override
  double extractDoubleValue(dynamic value, String? errMsg) =>
      (super.noSuchMethod(
            Invocation.method(#extractDoubleValue, [value, errMsg]),
            returnValue: 0.0,
          )
          as double);

  @override
  DateTime extractDateTime(dynamic value, String? errMsg) =>
      (super.noSuchMethod(
            Invocation.method(#extractDateTime, [value, errMsg]),
            returnValue: _FakeDateTime_4(
              this,
              Invocation.method(#extractDateTime, [value, errMsg]),
            ),
          )
          as DateTime);

  @override
  DateTime extractDateTimeFromEpochMs(dynamic value, String? errMsg) =>
      (super.noSuchMethod(
            Invocation.method(#extractDateTimeFromEpochMs, [value, errMsg]),
            returnValue: _FakeDateTime_4(
              this,
              Invocation.method(#extractDateTimeFromEpochMs, [value, errMsg]),
            ),
          )
          as DateTime);
}
